import os

#MAP
TILE_SIZE = 64
TILE_RESOLUTION = 16

MAX_BUFFER_SIZE = (1024, 1024)

CORNER_ROUNDING_ELEV_DELTA = 5
OPAQUE_TILE_ELEV_DELTA = 3
WALKING_TILE_ELEV_DELTA = 2

PLAYER_WALKING_SPEED = 5
SMOOTH_PLAYER_MOTION = True
PLAYER_INVENTORY_SIZE = 24
PLAYER_INVENTORY_WIDTH = 8

ITEM_LOCATION_AROUND_PLAYER = (48, -48)
