import os

#MAP
TILE_SIZE = 64
TILE_RESOLUTION = 16

MAX_BUFFER_SIZE = (2048, 2048)

CORNER_ROUNDING_ELEV_DELTA = 5
OPAQUE_TILE_ELEV_DELTA = 3
WALKING_TILE_ELEV_DELTA = 2

PLAYER_INVENTORY_SIZE = 24
PLAYER_INVENTORY_WIDTH = 8
